# Generated by Django 3.2.6 on 2021-12-14 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviedetails',
            name='poster',
        ),
    ]
